modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="clientinspector" #mandatory
version="2.0.0" #mandatory
displayName="Client Inspector" #mandatory
logoFile="examplemod.png" #optional
authors="Aquerr" #optional
description='''
A mod that inspects connecting players data and executes specified commands on them
https://github.com/Aquerr/ClientInspector
'''
[[dependencies.clientinspector]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.clientinspector]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
