# Conifg file for ClientInspector v2.0.3

# Set of commands that should be run against the player when 'mod list' is not received by the server.
# ClientInspector normally sends a modlist request to the ClientInspector located on the client side and awaits a response for the time specified in mod_list_await_time option.
# Use %PLAYER% placeholder to target the player. This placeholder will be replaced with the actual player by the plugin.
# Note: Don't put the slash "/" in front of the command.
# E.g. commands_to_run_when_modlist_not_received=["kick %PLAYER% ClientInspector not installed on the client side"]
commands_to_run_when_modlist_not_received = []

# The time in seconds to wait for mod list packet.
# When server does not get mod list packet from client it will execute commands_to_run_when_modlist_not_received on the client.
# Default: 10
mod_list_await_time=10

# Set of commands that should be run against the player after detecing a mod from the 'mods_to_detect' list.
# Use %PLAYER% placeholder to target the player. This placeholder will be replaced with the actual player by the plugin.
# Note: Don't put the slash "/" in front of the command.
# E.g. commands_to_run=["ban %PLAYER%", "jail %PLAYER% specialjail"]
commands_to_run = []

# Mods that plugin should search for in the connecting player's mod-list.
# Regex is supported and it preforms checks case-insensitive.
# E.g. Pattern ".*XRay.*" will match all mods names with word "xray".
# E.g. mods_to_detect=["forge", "xray", ".*xray.*", ".*cheats.*"]
mods_to_detect = [
    ".*xray.*"
]

# Makes "mods_to_detect" list being treated as whitelist instead of blacklist.
# That means, connecting player is REQUIRED to have ONLY mods that are listed in "mods_to_detect" list.
# Default: false
treat_mods_to_detect_as_whitelist=false